apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: block-controller
    app.kubernetes.io/version: v0.1.2
    app.kubernetes.io/managed-by: kustomize
  name: block-controller
  namespace: block-controller-system