  # ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: block-procscan
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: block-procscan
  subjects:
    - kind: ServiceAccount
      name: block-procscan
      namespace: block-system
