apiVersion: v1
kind: ConfigMap
metadata:
  name: procscan-aggregator-config
  namespace: block-system
data:
  config.yaml: |
    aggregator:
      scan_interval: "60s"
      port: 8090

    daemonset:
      namespace: "block-system"
      service_name: "procscan"
      # API 端口
      api_port: 9090
      # API 路径
      api_path: "/api/violations"

    # 日志配置
    logger:
      level: "info"
      format: "json"
